### ISSUE TITLE
Checklist for 2020 Proposal 

### ISSUE THREAD

**Issue by alvations** [nlposs/NLP-OSS#23]
Lets keep a checklist of the proposal w.r.t. to the requirements from https://acl2020.org/calls/workshops/ 

**First two pages:**

 - [x] A title and brief description of the workshop topic and content.

 - [x] A list of invited speakers, if applicable, with an indication of which ones have already agreed and which are indicative, and sources of funding for the speakers.

 - [x] An account of the efforts made to ensure demographic diversity of the organisers and speakers (WiNLP’s BIG Directory may be a useful resource). Also an account of any efforts to include diverse participants (e.g., via mentoring, subsidies, or the wording and topics in the CFP).

 - [x] An estimate of the number of attendees.

 - [x] A description of any shared tasks associated with the workshop, and estimate of the number of participants.

 - [x] A description of special requirements and technical needs.

 - [x] The preferred venue(s) (ACL/COLING/EMNLP/AACL-IJCNLP)

 - [x] Specify where previous workshops were held, 

 - [x] Specify how many submissions the workshop received,

 - [x] Specify how many papers were accepted

 - [x] Specify how many attendees the workshop attracted.

**Next two pages:**

 - [x] Organizers' names, affiliations, and email addresses, with one-paragraph statements of their research interests, areas of expertise, and experience in organising workshops and related events.

 - [x] Programme Committee members, with an indication of which members have already agreed. It is highly desirable for proposals to have at least 75% of the Programme Committee reviewers confirmed

 - [x] References

**On START, we need these info:**

 - [x] A very brief advertisement or tagline for the workshop, up to 140 characters, that highlights any key information you wish prospective attendees to know, and which would be suitable to be put onto a web-based survey 

 - [x] A URL for the workshop website which will be shown in the web-based survey.

 - [x] A list of organizers’ names which will be shown in the web-based survey.

Also, we need to update the site after the submission.

**Comment by alvations** [comment]
Here's the first draft of the four page proposal, [google doc](https://docs.google.com/document/d/1JMU8-MRxK55d9FJttXgC5Q17Mh7r4vhG55thg5I8nHk/edit?usp=sharing). Feel free to comment or tell us if you catch any typo! 

We'll still need a tag line, previously we went with `Democratizing NLP!`, maybe we'll come up with something else this time? @everyone any suggestion?

As for URL, we still have some post-proposal submission task to refactor the https://github.com/nlposs/nlposs.github.io page but I think for now, we can stay with https://nlposs.github.io (with reference to the 2018 workshop) =)

**Comment by ggdupont** [comment]
"NLP for humans"
(surprisingly not taken already...)

**Comment by goodmami** [comment]
> "NLP for humans"

This is nice but it sounds more like a user-friendly NLP package to me. If we adjust it a little bit, we can capture more of the inclusive spirit of OSS: "NLP for Everyone". Google does get some hits for this slogan, but they seems related to the *other* "NLP".

@alvations I made a few edits to the Google Doc for mostly minor issues

**Comment by alvations** [comment]
Thank you @goodmami !

@ggdupont maybe "for humans" sounds a little odd and doesn't have much direct mental connection to OSS.

**Comment by ggdupont** [comment]
> maybe "for humans" sounds a little odd

Possible, I'm not a native English speaker ;-)
I meant it in line with the "NLP for Everyone" spirit.

**Comment by alvations** [comment]
I think for now, there's no strong support for any change for the tagline. So we've submitted the same tagline we used in 2018, `Democratizing NLP!`

Thank you @ggdupont @goodmami for you inputs for the tagline. 

Submitted the proposal to the ACL/COLING/EMNLP/AACL-IJCNLP 2020 call for proposal.
Fingers crossed!

Thank you @everyone for helping with the proposal and a big thanks to all PC members who have accepted our invitation for the NLP-OSS 2020!!

**Comment by alvations** [comment]
I guess some of you have already heard the news. We're going to be at EMNLP 2020!! 

@PCMembers, we'll update you soon with an email notification. 

@Everyone, hope to see your submission to the workshop and also at the workshop too.

Thank you all for crafting the successful proposal.
